// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// arma_qr
SEXP arma_qr(const arma::mat& X);
RcppExport SEXP _uca_arma_qr(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(arma_qr(X));
    return rcpp_result_gen;
END_RCPP
}
// arma_svd
SEXP arma_svd(const arma::mat& X);
RcppExport SEXP _uca_arma_svd(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(arma_svd(X));
    return rcpp_result_gen;
END_RCPP
}
// arma_score
SEXP arma_score(const arma::mat& A, const arma::mat& B);
RcppExport SEXP _uca_arma_score(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(arma_score(A, B));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_uca_arma_qr", (DL_FUNC) &_uca_arma_qr, 1},
    {"_uca_arma_svd", (DL_FUNC) &_uca_arma_svd, 1},
    {"_uca_arma_score", (DL_FUNC) &_uca_arma_score, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_uca(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
