// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// arma_qr
SEXP arma_qr(const arma::mat& X);
RcppExport SEXP _uca_arma_qr(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(arma_qr(X));
    return rcpp_result_gen;
END_RCPP
}
// arma_svd
SEXP arma_svd(const arma::mat& X);
RcppExport SEXP _uca_arma_svd(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(arma_svd(X));
    return rcpp_result_gen;
END_RCPP
}
// arma_score
SEXP arma_score(const arma::mat& A, const arma::mat& B);
RcppExport SEXP _uca_arma_score(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(arma_score(A, B));
    return rcpp_result_gen;
END_RCPP
}
// broken_svd_cpp
SEXP broken_svd_cpp(const arma::mat& left, const arma::mat& right, const int& nv);
RcppExport SEXP _uca_broken_svd_cpp(SEXP leftSEXP, SEXP rightSEXP, SEXP nvSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type left(leftSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type right(rightSEXP);
    Rcpp::traits::input_parameter< const int& >::type nv(nvSEXP);
    rcpp_result_gen = Rcpp::wrap(broken_svd_cpp(left, right, nv));
    return rcpp_result_gen;
END_RCPP
}
// multiple_score_calc_cpp
SEXP multiple_score_calc_cpp(const arma::mat& left, const arma::mat& right, const arma::mat& right_u, const arma::vec& right_d);
RcppExport SEXP _uca_multiple_score_calc_cpp(SEXP leftSEXP, SEXP rightSEXP, SEXP right_uSEXP, SEXP right_dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type left(leftSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type right(rightSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type right_u(right_uSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type right_d(right_dSEXP);
    rcpp_result_gen = Rcpp::wrap(multiple_score_calc_cpp(left, right, right_u, right_d));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_uca_arma_qr", (DL_FUNC) &_uca_arma_qr, 1},
    {"_uca_arma_svd", (DL_FUNC) &_uca_arma_svd, 1},
    {"_uca_arma_score", (DL_FUNC) &_uca_arma_score, 2},
    {"_uca_broken_svd_cpp", (DL_FUNC) &_uca_broken_svd_cpp, 3},
    {"_uca_multiple_score_calc_cpp", (DL_FUNC) &_uca_multiple_score_calc_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_uca(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
