---
title: "rPCA methylation"
author: "Robin Tu"
date: "12/15/2019"
output:
  pdf_document:
    toc: yes
  html_document:
    code_folding: hide
    collapsed: no
    toc: yes
    toc_float: yes
---


```{r setup, include=FALSE}
library("data.table")
library("ggplot2")
library("gridExtra")
library("splines")
options(scipen = -2, digits =3)
theme_set(theme_bw())
#theme_set(theme_bw())
function_dir <- "../functions/"
sapply(list.files(function_dir), function(xx) source(paste0(function_dir, xx)))
```

# Exploring contrastive PCA in methylation data

## Reading Data in

```{R}
blood <- fread("../../methylation/data/all_blood_BMIQ_comBAT_QN_sep_gf.csv")
fc <- fread("../../methylation/data/frontal cortex_BMIQ_comBAT_QN_sep_gf.csv")
ba10 <- fread("../../methylation/data/BRAIN10_BMIQ_comBAT_QN_gf.csv")
pd <- fread("../../methylation/data/all_pd.csv")
```

## Setting up data 

```{R}
disease_stat <- pd[, .(disease = unique(disease)), by = subject]
setkey(disease_stat, "subject")

setkeyv(blood, c("geneSymbol","feature","probe","subject"))
setkeyv(fc, c("geneSymbol","feature","probe","subject"))
setkeyv(ba10, c("geneSymbol","feature","probe","subject"))

combined <- merge(blood,
                  rbind(fc, ba10),
                  all = T)
combined <- combined[complete.cases(combined)]
combined <- merge(combined,disease_stat, by = "subject")

setnames(combined, old = c("value.x","value.y"), new = c("blood","brain"))
features <- c("1stExon", "5'UTR", "Body", "TSS1500", "TSS200", "3'UTR" )

rm(list = c("blood","fc","ba10"))
```


```{R}
avg_combined <- combined[, .(blood = mean(blood),
                             brain = mean(brain),
                             disease = unique(disease),
                             group = substr(subject,1,1)
), by = c("geneSymbol", "subject", "feature")]
setkeyv(avg_combined, c("geneSymbol", "subject","feature","disease","group"))
```

# Contrasting Disease vs. Nondiseased Brain, then projecting all blood

to see if we get a difference. Differences found is from the data sets more than from disease vs nondisease


```{R}
# 
feat = 1;
bg_brain <- dcast(formula = subject ~ geneSymbol, data = avg_combined[(feature == features[feat]) & (disease == 0)], value.var = "brain")[, subject := NULL]

targ_brain <- dcast(formula = subject ~ geneSymbol, data = avg_combined[(feature == features[feat])& (disease == 1)], value.var = "brain")[, subject := NULL]

rPCA_fExon_brain <- rPCA(target = targ_brain, bg = bg_brain, n_components = 2, bg_components = c(2:3), return_all = F)

rPCA_fExon_plot <- data.table(avg_combined[disease !=0, .(disease = as.factor(unique(disease))), by = subject], rPCA_fExon_brain$reduced_target)
rPCA_fExon_plot[,group:= substr(subject,start = 1,stop =1)]

setnames(rPCA_fExon_plot, old = c("V1", "V2"), c("rPC1","rPC2"))

ggplot(data = rPCA_fExon_plot)+
  geom_point(aes(x = rPC1, y=rPC2, color = disease, shape = group))
```

projecting all the blood data onto the directions found from the rPC in brain to see if we can get some nice seperation 

```{R}
blood_temp <- dcast(formula = subject ~ geneSymbol, data = avg_combined[feature == features[feat]], value.var = "blood")[, subject := NULL]

blood_loadings <- cbind(data.matrix(blood_temp) %*% rPCA_fExon_brain$res_target_svd, "rPCA")
blood_loadings_plot <- data.table(blood_loadings, avg_combined[, .(disease = unique(disease)), by = subject])[,disease := as.factor(disease)]

blood_pca <- cbind(data.matrix(blood_temp) %*% svd(data.matrix(blood_temp),nv =2)$v, "PCA")
blood_pca_plot <- data.table(blood_pca, avg_combined[, .(disease = unique(disease)), by = subject])[,disease := as.factor(disease)]

combined_plot <- rbind(blood_loadings_plot, blood_pca_plot)
setnames(combined_plot, old = c("V1","V2","V3"), new = c("X","Y","Method"))
combined_plot[,`:=`(group = substr(subject,start = 1, stop =1),
                    Method = as.factor(Method))]


ggplot(data = combined_plot, aes(x = X, y=Y))+
  geom_point(aes(color = disease, shape=group))+
  facet_wrap(~Method)+
  theme(legend.position = "bottom")
```

# Contrasting Disease vs. Nondiseased Blood, then projecting Hannon Brain

This is because blood is exactly the same in both data sets.  Perhaps blood is directly related with alzhimers we can learn something about the brain.

```{R}
blood_no_disease <- dcast(formula = subject ~ geneSymbol, data = avg_combined[feature == features[feat] & disease == 0], value.var = "blood")[, subject := NULL]

blood_disease <- dcast(formula = subject ~ geneSymbol, data = avg_combined[feature == features[feat] & disease == 1], value.var = "blood")[, subject := NULL]

blood_disease_rpca <- rPCA(target = blood_disease, bg = blood_no_disease, n_components = 2, return_all = T)

brain_all <- dcast(subject ~ geneSymbol, value.var = "brain", data = avg_combined[feature==features[feat]])[, subject := NULL]

brain_on_blood_plot <- data.table(avg_combined[,.(disease = unique(disease),
                group = unique(group)), by = subject], 
data.matrix(brain_all) %*% blood_disease_rpca$res_target_svd)

setnames(brain_on_blood_plot, c("V1","V2"), c("rPC1","rPC2"))

ggplot(data = brain_on_blood_plot, aes(x = rPC1, y = rPC2))+
  geom_point(aes(color = as.factor(disease), shape = group))+
  theme(legend.position = "bottom")+
  labs(title = "Brain data projected onto the directions found by rPCA\n with Blood Diseased as target and Blood non-diseased as background")
```



# contrasting edgar only, projecting hannon brain
Only used edgar as the background and target. Then Projecting Hannon Brain

```{R}
edgar_blood <- dcast(subject~geneSymbol, value.var = "blood", data = avg_combined[group == "E" & feature == features[feat]])[,subject:=NULL]

edgar_brain <- dcast(subject~geneSymbol, value.var = "brain", data = avg_combined[group == "E" & feature == features[feat]])[,subject:=NULL]

edgar_rPCA <- rPCA(target = edgar_brain, bg = edgar_blood, n_components = 2, return_all = T)

hannon_brain <- dcast(subject~geneSymbol, value.var = "brain", data = avg_combined[group =="H" & feature ==features[feat]])

hannon_subject_disease <- disease_stat[subject %in% hannon_brain[,subject]]
hannon_brain[,subject := NULL]

hannon_brain_projected_dat <- data.table(hannon_subject_disease, rbind(cbind(data.matrix(hannon_brain)%*% edgar_rPCA$res_target_svd,"rPCA"),
      cbind(data.matrix(hannon_brain)%*% svd(data.matrix(hannon_brain),nv = 2)$v, "PCA")))

setnames(hannon_brain_projected_dat, c("subject","disease","X", "Y","Method"))

ggplot(data = hannon_brain_projected_dat)+
  geom_point(aes(x = X, y = Y, color = as.factor(disease)))+
  facet_grid(.~Method)+
  theme(legend.position = "bottom")
```

#contrasting hannon only brain, to see if there's a difference

```{R}
hannon_blood <- dcast(subject~geneSymbol, value.var = "blood", data = avg_combined[group =="H" & feature == features[feat]])[,subject := NULL]

hannon_brain_disease <- dcast(subject~geneSymbol, value.var = "brain", data = avg_combined[group =="H" & feature == features[feat] & disease == 1])[,subject := NULL]

hannon_brain_control <- dcast(subject~geneSymbol, value.var = "brain", data = avg_combined[group =="H" & feature == features[feat] & disease == 0])[,subject := NULL]

rPCA_hannon_brain <- rPCA(target = hannon_brain_disease, bg = hannon_brain_control, n_components = 2, return_all = T)
rPCA_hannon_blood <- cbind(data.matrix(hannon_blood) %*% rPCA_hannon_brain$res_target_svd, "rPCA")
PCA_hannon_blood <- cbind(data.matrix(hannon_blood) %*% svd(hannon_blood, nv=2)$v, "PCA")

hannon_blood_projected <- data.table(hannon_subject_disease, rbind(rPCA_hannon_blood, PCA_hannon_blood))
setnames(hannon_blood_projected, c("V1","V2","V3"), c("X", "Y", "Method"))

ggplot(data = hannon_blood_projected, aes(x = X, y = Y))+
  geom_point(aes(color = as.factor(disease)))+
  facet_wrap(~Method)+
  theme(legend.position = "bottom")

```

