---
title: "kdef_stacking_target"
author: "Robin Tu"
date: "5/3/2020"
output: html_document
---

```{r setup, include=FALSE}
rm(list = ls())
#Sys.setenv(MKL_DEBUG_CPU_TYPE=5, MKL_VERBOSE=1) #intel MKL settings. latter to hack amd processors
install.packages("../uca_0.12.zip", repos = NULL, type="source")
libraries <- c("data.table", "MASS", "ggplot2", "splines","gridExtra", "uca", "imager", "future", "RSpectra", "microbenchmark")

lapply(libraries, library, character.only = T)
plan(multiprocess)
```

## Helper functions 

```{R}
# read images into R
readImage <- function(listFiles, size_x, size_y){
 loaded_images <- lapply(listFiles, load.image)
 grey_scaled <- lapply(loaded_images, function(zz) scale(as.data.frame(resize(grayscale(zz), size_x, size_y))[,3]))
 return(data.matrix(do.call(cbind,grey_scaled)))
}

# Turn Eigenvectors to eigenfaces
toEigenfaces <- function(dat, size_x = 58, size_y = 68){
  eigenfaces <- data.table(do.call(rbind,
                        lapply(1:ncol(dat), function(zz){
  cbind(as.data.frame(as.cimg(dat[,zz], dim = c(size_x, size_y,1,1))), zz)
})))
  setnames(eigenfaces,c("x","y","value","Eigenface"))
  eigenfaces[, value2 := 2*(value - min(value))/(max(value) - min(value)), by = Eigenface]
  return(eigenfaces)
}

plotEigenfaces = function(eigenfaces, title, nrow){
  ggplot(eigenfaces, aes(x,y))+
geom_raster(aes(fill = value))+
  facet_wrap(~Eigenface, nrow = nrow)+
scale_x_continuous(expand=c(0,0))+
  scale_y_continuous(expand=c(0,0),trans=scales::reverse_trans())+
   scale_fill_gradient(low="black", high="white")+
  labs(title = title)
}

plotEigenfaces2 <- function(eigenfaces, title){
  ggplot(eigenfaces, aes(x,y))+
geom_raster(aes(fill = value))+
  facet_grid(alpha~Eigenface)+
scale_x_continuous(expand=c(0,0))+
  scale_y_continuous(expand=c(0,0),trans=scales::reverse_trans())+
   scale_fill_gradient(low="black", high="white")+
  labs(title = title)
}

readImageRotate <- function(listFiles, rotation, size_x, size_y){
 loaded_images <- lapply(listFiles, load.image)
 grey_scaled <- lapply(seq_along(loaded_images), function(zz) scale(as.data.frame(resize(grayscale(imrotate(loaded_images[[zz]], rotation[[zz]])), size_x, size_y))[,3]))
 return(data.matrix(do.call(cbind,grey_scaled)))
}

# make faces positively correlated with reference data
pos_corr <- function(dat, ref_dat){
  sapply(1:ncol(dat), function(zz){
    current_sign <- sign(cor(dat[,zz], ref_dat[,zz]))
    if(current_sign == -1){
      return(-dat[,zz])
    }else{
      return(dat[,zz])
    }
    })
}


kdef <- "KDEF_and_AKDEF/KDEF/"
```

# Happy faces

```{R}
happy_straight_files <- paste0(kdef, sapply(list.files(kdef), function(zz) paste0(zz,"/",zz,"HAS.JPG")))
happy_left_files <- paste0(kdef, sapply(list.files(kdef), function(zz) paste0(zz,"/",zz,"HAHL.JPG")))
happy_right_files <- paste0(kdef, sapply(list.files(kdef), function(zz) paste0(zz,"/",zz,"HAHR.JPG")))

happy_straight %<-% readImage(happy_straight_files, 25, 34)
happy_left %<-% readImage(happy_left_files, 25, 34)
happy_right %<-% readImage(happy_right_files, 25, 34)

t_HS %<-% Rfast::transpose(happy_straight)
t_HL %<-% Rfast::transpose(happy_left)
t_HR %<-% Rfast::transpose(happy_right)

t_stack_HLR %<-% rbind(t_HL, t_HR)
t_stack_HCLR %<-% rbind(t_HS, t_HL, t_HR)

# cov_happy_straight %<-% cov(t_HS)
# cov_happy_left %<-% cov(t_HL)
# cov_happy_right %<-% cov(t_HR)
# cov_happy_stack_HLR %<-% cov(t_stack_HLR)
# cov_happy_stack_HCLR %<-% cov(t_stack_HCLR)
```

#Neutral Faces

```{R}
neutral_straight_files <- paste0(kdef, sapply(list.files(kdef), function(zz) paste0(zz,"/",zz,"NES.JPG")))
neutral_left_files <- paste0(kdef, sapply(list.files(kdef), function(zz) paste0(zz,"/",zz,"NEHL.JPG")))
neutral_right_files <- paste0(kdef, sapply(list.files(kdef), function(zz) paste0(zz,"/",zz,"NEHR.JPG")))

neutral_straight %<-% readImage(neutral_straight_files, 25, 34)
neutral_left %<-% readImage(neutral_left_files, 25, 34)
neutral_right %<-% readImage(neutral_right_files, 25, 34)

t_NS <- Rfast::transpose(neutral_straight)
t_NL <- Rfast::transpose(neutral_left)
t_NR <- Rfast::transpose(neutral_right)

```

# check indeed all have mean zero after centering

```{R}
head(sapply(list(t_HS, t_HL, t_HR), colMeans))
```

# Plot generic eigenfaces

```{R}
eigenface_HS <- eigs_sym(cov_happy_straight, 5, "LA")
eigenface_HS_plot <- toEigenfaces(eigenface_HS$vectors)
eigenface_HL <- eigs_sym(cov_happy_left, 5, "LA")
eigenface_HL_plot <- toEigenfaces(eigenface_HL$vectors)
eigenface_HR <- eigs_sym(cov_happy_right, 5, "LA")
eigenface_HR_plot <- toEigenfaces(eigenface_HR$vectors)
eigenface_HLR <- eigs_sym(cov_happy_stack_HLR, 5, "LA")
eigenface_HLR_plot <- toEigenfaces(eigenface_HLR$vectors)
eigenface_HCLR <- eigs_sym(cov_happy_stack_HCLR, 5, "LA")
eigenface_HCLR_plot <- toEigenfaces(eigenface_HCLR$vectors)


eigenface_happy_LR_plot <- rbind(eigenface_HL_plot[, alpha:= "Left"],
                                 eigenface_HR_plot[, alpha:= "right"],
                                 eigenface_HS_plot[, alpha := "Center"],
                                 eigenface_HLR_plot[, alpha:= "Left/Right Stack"],
                                 eigenface_HCLR_plot[, alpha := "Center/Left/Right Stack"])

ggsave("results/happy_eigenfaces_center-left-right.png", plotEigenfaces2(eigenface_happy_LR_plot, "Happy Eigenfaces Center/Left/Right"),width = 10, height = 11, units = "in")
```

# equal sample sizes for all groups

```{R}
stack_HCLR_L %<-% uca(t_stack_HCLR, list(t_HL), nv = 5, method = "data")
stack_HCLR_R %<-% uca(t_stack_HCLR, t_HR, nv = 5, method = "data")
stack_HCLR_LR %<-% uca(t_stack_HCLR, list(t_HL, t_HR), nv = 5, method = "data")
stack_HCLR_LR_stack %<-% uca(t_stack_HCLR, t_stack_HLR, nv = 5, method = "data")


HCLR_L_plot <- toEigenfaces(stack_HCLR_L$vectors)[, alpha:= "Left"]
HCLR_R_plot <- toEigenfaces(stack_HCLR_R$vectors)[, alpha:= "Right"]
HCLR_LR_plot <- toEigenfaces(stack_HCLR_LR$vectors)[, alpha:= "Left/Right Split"]
HCLR_LR_stack_plot <- toEigenfaces(stack_HCLR_LR_stack$vectors)[, alpha:= "Left/Right Stack"]
HCLR_split_stack_diff_plot <- toEigenfaces(image_diff(stack_HCLR_LR_stack$vectors, stack_HCLR_LR$vectors))[, alpha := "vDiff"]
stack_HCLR_various_bg_plot <- rbind(HCLR_L_plot,HCLR_R_plot, HCLR_LR_plot, HCLR_LR_stack_plot,HCLR_split_stack_diff_plot)

ggsave("results/stack-HCLR-various-bg.png", plotEigenfaces2(stack_HCLR_various_bg_plot, "Stack Center/Left/Right with Various Background"),width = 10, height = 11, units = "in")
```

make the stacked covariance washout signal from both straight and left. we use 1/10th sample size of both left and straight so right face dominates.

```{R, message = FALSE}
t_HS_sub_sample <- sample(1:nrow(t_HS), size = 10)
t_HL_sub_sample <- sample(1:nrow(t_HL), size = 35)

t_HS.sub %<-% t_HS[t_HS_sub_sample, ]
t_HL.sub %<-% t_HL[t_HL_sub_sample, ]
t_stack_HLR_sub %<-% do.call(rbind, list(t_HL.sub, t_HR))
t_stack_HCLR_sub %<-% rbind(t_HS.sub,t_stack_HCLR_sub)

t_stack_HCLR_sub_vectors <- eigs_sym(cov(t_stack_HCLR_sub), 5, "LA")$vectors
t_stack_HLR_sub_vectors <- eigs_sym(cov(t_stack_HLR_sub), 5, "LA")$vectors

uca_LR_stack_vectors <- uca(t_stack_HCLR_sub, t_stack_HLR_sub, 5, method = "data")$vectors
uca_LR_split_vectors <- uca(t_stack_HCLR_sub, list(t_HL.sub, t_HR), 5, method = "data")$vectors


t_stack_HLR_sub_plot <- toEigenfaces(t_stack_HLR_sub_vectors)[,alpha := "PCA LR"]
t_stack_HCLR_sub_plot <- toEigenfaces(t_stack_HCLR_sub_vectors)[,alpha := "PCA CLR"]
uca_LR_stack_sub_plot <- toEigenfaces(uca_LR_stack_vectors)[, alpha := "UCA LR Stack"]
uca_LR_split_sub_plot <- toEigenfaces(uca_LR_split_vectors)[, alpha := "UCA LR Split"]
uca_LR_split_stack_sub_diff <- toEigenfaces(image_diff(uca_LR_stack_vectors, uca_LR_split_vectors))[, alpha := "vDiff"]

plotEigenfaces2(rbind(t_stack_HLR_sub_plot,t_stack_HCLR_sub_plot,uca_LR_stack_sub_plot,uca_LR_split_sub_plot,uca_LR_split_stack_sub_diff), "tmp")

```


denoise full data via construct some background that's just an a ton of random stuff.

```{R, message = FALSE}
t_HL_sub_sample <- sample(1:nrow(t_HL), size = 30)
t_HL.sub %<-% t_HL[t_HL_sub_sample, ]
t_stack_HLR_sub %<-% do.call(rbind, list(t_HL.sub, t_HR))
t_stack_HCLR_vectors <- eigs_sym(cov(t_stack_HCLR), 5, "LA")$vectors
t_stack_HLR_vectors <- eigs_sym(cov(t_stack_HLR_sub), 5, "LA")$vectors

uca_LR_stack_all_vectors <- uca(t_stack_HCLR, t_stack_HLR_sub, 5, method = "data")$vectors
uca_LR_split_all_vectors <- uca(t_stack_HCLR, list(t_HL.sub, t_HR), 5, method = "data")$vectors

t_stack_HLR_plot <- toEigenfaces(t_stack_HLR_vectors)[,alpha := "PCA LR"]
t_stack_HCLR_plot <- toEigenfaces(t_stack_HCLR_vectors)[,alpha := "PCA CLR"]
uca_LR_stack_all_sub_plot <- toEigenfaces(uca_LR_stack_all_vectors)[, alpha := "UCA LR Stack"]
uca_LR_split_all_sub_plot <- toEigenfaces(uca_LR_split_all_vectors)[, alpha := "UCA LR Split"]
LR_stack_split_plot <- toEigenfaces(image_diff(uca_LR_stack_all_vectors, uca_LR_split_all_vectors))[, alpha:= "vDiff"]

plotEigenfaces2(rbind(uca_LR_stack_all_sub_plot, uca_LR_split_all_sub_plot), "tmp")

ggsave("results/all_CLR_30-L_All-R.png", plotEigenfaces2(rbind(t_stack_HLR_plot,t_stack_HCLR_plot,uca_LR_stack_all_sub_plot,uca_LR_split_all_sub_plot,LR_stack_split_plot), "Target: Happy - All Straight, Left, Right. Background: 30 Left, all Right"), width = 10, height = 11, units = "in")

```

making up another full data set like the one above and hoping for similar results

target:angry
background: sad/disgust split/stack

seems like a lot of information could be encoded in `sad` such that small data from disgust really doesn't help recover more of angry

```{R}
t_angry %<-% center_f(t(angry))
t_sad %<-% center_f(t(sad))
t_disgust %<-% center_f(t(disgust))

t_sad_sub %<-% t_sad[sample(1:nrow(t_sad), 3),]


stack_SAD <- do.call(rbind, list(t_angry, t_sad, t_disgust))
stack_SD <- rbind(t_sad, t_disgust)
stack_SD_sub <- rbind(t_sad_sub, t_disgust)

pca_SAD <- eigs_sym(cov(stack_SAD), 5, "LA")$vectors
uca_SAD_SD_split <- uca(stack_SAD, list(t_sad_sub, t_disgust), nv = 5, method = "data")$vectors
uca_SAD_SD_stack <- uca(stack_SAD, stack_SD_sub, nv = 5, method = "data")$vectors
uca_SAD_SD_diff <- image_diff(uca_SAD_SD_stack, uca_SAD_SD_split)

pca_SAD_plot <- toEigenfaces(pca_SAD)[, alpha := "PCA"]
uca_SAD_SD_split_plot <- toEigenfaces(uca_SAD_SD_split)[, alpha := "Split"]
uca_SAD_SD_stack_plot <- toEigenfaces(uca_SAD_SD_stack)[, alpha := "Stack"]
uca_SAD_SD_diff_plot <- toEigenfaces(uca_SAD_SD_diff)[, alpha := "vDiff"]

ggsave("results/CSAD_3-S_All-D.png", plotEigenfaces2(rbind(pca_SAD_plot,uca_SAD_SD_split_plot,uca_SAD_SD_stack_plot,uca_SAD_SD_diff_plot), "Target: Stack Sad/Angry/Disgust, Background: Sad/Disgust Split/Stack"), width = 10, height = 11, units = "in")
```

* mixing target with different faces


* constructing background with noise

```{R}
H_noise <- matrix(rnorm(prod(dim(t_HS))),nrow = nrow(t_HS)) 
stack_HLRN <- rbind(t_stack_HLR, H_noise)

pca_HLRN <- eigs_sym(cov(stack_HLRN), 5, "LA")$vectors #what happens when you add noise...
uca_HCLR_stack_LRN <- uca(t_stack_HCLR, stack_HLRN, nv = 5, method = "data")$vectors
uca_HCLR_split_LR_N <- uca(t_stack_HCLR, list(H_noise, t_stack_HLR), nv = 5, method = "data")$vectors
uca_HCLR_split_L_R_N <- uca(t_stack_HCLR, list(H_noise, t_HL, t_HR), nv = 5, method = "data")$vectors
LRN_L_R_N_diff <- image_diff(uca_HCLR_stack_LRN, uca_HCLR_split_L_R_N)
LR_N_L_R_N_diff <- image_diff(uca_HCLR_split_LR_N, uca_HCLR_split_L_R_N)

pca_HLRN_plot <- toEigenfaces(pca_HLRN)[,alpha := "PCA LRN Stack"]
uca_HCLR_stack_LRN_plot <- toEigenfaces(uca_HCLR_stack_LRN)[, alpha := "UCA LRN Stack"]
uca_HCLR_split_LR_N_plot <- toEigenfaces(uca_HCLR_stack_LRN)[, alpha := "UCA LR_N Split"]
uca_HCLR_split_L_R_N_plot <- toEigenfaces(uca_HCLR_stack_LRN)[, alpha := "UCA L_R_N Split"]
LRN_L_R_N_diff_plot <- toEigenfaces(LRN_L_R_N_diff)[,alpha:= "vDiff(LRN - L_R_N)"]
LR_N_L_R_N_diff_plot <- toEigenfaces(LR_N_L_R_N_diff)[, alpha := "vDiff(LR_N - L_R_N)"]

ggsave("HCLR_stack_1x_Noise.png",plotEigenfaces2(do.call(rbind, list(pca_HLRN_plot,uca_HCLR_stack_LRN_plot,uca_HCLR_split_LR_N_plot,uca_HCLR_split_L_R_N_plot,LRN_L_R_N_diff_plot, LR_N_L_R_N_diff_plot)), "Target: Happy CLR stack, Background: L/R/Noise Combinations. 1x Noise"),
       width = 10, height = 11, units = "in")
```


Lots of noise

```{R}
H_noise2 <- matrix(rnorm(25*prod(dim(t_HS))),ncol = ncol(t_HS)) 
ut_HR_sub <- ut_HR[sample(1:nrow(ut_HR), size = 20),]
ut_HL_sub <- ut_HL[sample(1:nrow(ut_HL), size = 20),]
u_stack_HLRN <- rbind(H_noise2, ut_HR_sub, ut_HL_sub)
ut_stack_HCLR %<-% rbind(t(happy_straight), t(happy_left), t(happy_right))

pca_stack_CLR <- svds(ut_stack_HCLR, k = 5, which = "LA")$v
pca_stack_CLR_plot <- toEigenfaces(pca_stack_CLR)[,alpha := "PCA CLR Stack"]
pca_HLRN <- svds(center_f(u_stack_HLRN),k = 5, which = "LA")$v #what happens when you add noise...
pca_HLRN_plot <- toEigenfaces(pca_HLRN)[,alpha := "PCA LRN Stack"]

uca_HCLR_stack_LRN <- uca(ut_stack_HCLR, u_stack_HLRN, nv = 5, method = "data", limit = 1000, center = T)
uca_HCLR_split_LR_N <- uca(ut_stack_HCLR, list(H_noise2, ut_stack_HLR), nv = 5, method = "data", center = T)
uca_HCLR_split_L_R_N <- uca(ut_stack_HCLR, list(H_noise2, ut_HR_sub,ut_HL_sub), nv = 5, method = "data", limit = 1000, center = T)
LRN_L_R_N_diff <- image_diff(uca_HCLR_stack_LRN$vectors, uca_HCLR_split_L_R_N$vectors)
LR_N_L_R_N_diff <- image_diff(uca_HCLR_split_LR_N$vectors, uca_HCLR_split_L_R_N$vectors)

uca_HCLR_stack_LRN_plot <- toEigenfaces(uca_HCLR_stack_LRN$vectors)[, alpha := "UCA LRN Stack"]
uca_HCLR_split_LR_N_plot <- toEigenfaces(uca_HCLR_stack_LRN$vectors)[, alpha := "UCA LR_N Split"]
uca_HCLR_split_L_R_N_plot <- toEigenfaces(uca_HCLR_stack_LRN$vectors)[, alpha := "UCA L_R_N Split"]

LRN_L_R_N_diff_plot <- toEigenfaces(LRN_L_R_N_diff)[,alpha:= "vDiff(LRN - L_R_N)"]
LR_N_L_R_N_diff_plot <- toEigenfaces(LR_N_L_R_N_diff)[, alpha := "vDiff(LR_N - L_R_N)"]


ggsave("results/HCLR_stack_25x_Noise_20L20R.png",plotEigenfaces2(do.call(rbind, list(pca_stack_CLR_plot, pca_HLRN_plot,uca_HCLR_stack_LRN_plot,uca_HCLR_split_LR_N_plot,uca_HCLR_split_L_R_N_plot,LRN_L_R_N_diff_plot, LR_N_L_R_N_diff_plot)), "Target: Happy CLR stack, Background: L/R/Noise Combinations. 25x noise"),
       width = 10, height = 11, units = "in")
```


```{R}
uca_HCLR_split_L_R_N$tau
```

* Target: L/R happy
* Background: Left+Right Neutral Noise
* Right Noise: Right faces with random 90 degree rotations

Hope to recover right faces better in splitting than stacking

```{R}
rotate <- sample(c(1:3)*90, size = length(neutral_right_files), replace = T)
neutral_right_rotate <- readImageRotate(neutral_right_files, rotate, 25, 34)

right_noise <- Rfast::transpose(neutral_right_rotate)
stack_l_rn <- rbind(t_HL[1:20, ], right_noise)

svd_t_stack_HLR <- svds(scale(t_stack_HLR), k = 5, which = "LA")
svd_lrn <- svds(scale(stack_l_rn), k = 5, which = "LA")
uca_stack_lr_lrn <- uca(t_stack_HLR, stack_l_rn, nv = 5, scale = T, limit = 50)
uca_split_lr_l_rn <- uca(t_stack_HLR, list(t_HL[1:20,], right_noise), nv = 5, scale = T, limit = 100)

pos_uca_stack_lr_lrn <- pos_corr(uca_stack_lr_lrn$vectors, uca_split_lr_l_rn$vectors)
diff_uca_stack_lr_lrn <- pos_uca_stack_lr_lrn - uca_split_lr_l_rn$vectors

LR_rotate_plot <- plotEigenfaces2(rbind(
toEigenfaces(svd_t_stack_HLR$v)[, alpha := "PCA Target"],
toEigenfaces(svd_lrn$v)[, alpha := "PCA LRN"],
toEigenfaces(pos_uca_stack_lr_lrn)[, alpha:= "Stack"],
toEigenfaces(uca_split_lr_l_rn$vectors)[, alpha := "Split"],
toEigenfaces(diff_uca_stack_lr_lrn)[, alpha := "diff"]), "Target: Happy L/R.  Bg: Neutral L/R.Rotate")

ggsave("results/Happy_LR_Neutral_L_RRotate_20L70R.png",LR_rotate_plot, width = 10, height = 11, units = "in")

```


* Target: L/R
* Background: Left+Noise
* Noise: Uniform(0,1)

```{R}
unif_noise_01 <- matrix(runif(n = 1*prod(dim(t_NL))), ncol = ncol(t_NL))
stack_unif01_l <- rbind(unif_noise_01, t_NL[1:20,])


uca_stack_lr_lunif01 <- uca(t_stack_HLR, stack_unif01_l, nv = 5, scale = T, limit = 100)
uca_split_lr_l_unif01 <- uca(t_stack_HLR, list(unif_noise_01, t_NL[1:20,]), nv = 5, scale = T, limit = 100)
pos_stack_lr_lunif01 <- pos_corr(uca_stack_lr_lunif01$vectors, uca_split_lr_l_unif01$vectors)
diff_stack_lr_lunif01 <- pos_stack_lr_lunif01 - uca_split_lr_l_unif01$vectors

LR_unif_01_plot <- plotEigenfaces2(
rbind(
toEigenfaces(svd_t_stack_HLR$v)[, alpha := "PCA Target"],
toEigenfaces(svds(scale(stack_unif01_l), k = 5, which ="LA" )$v)[, alpha:= "PCA Stack"],
toEigenfaces(pos_stack_lr_lunif01)[, alpha := "Stack 0-1"],
toEigenfaces(uca_split_lr_l_unif01$vectors)[, alpha := "Split 0-1"],
toEigenfaces(diff_stack_lr_lunif01)[, alpha := "Diff"]), title = "Target: Happy L/R. Bg: Neutral L and Uniform 0-1 Noise")

ggsave("results/LR_20L_1x_unif01.png", LR_unif_01_plot,  width = 10, height = 11, units = "in")


```

* Noise: Uniform(-10, 10)


```{R}
unif_noise_1010 <- matrix(runif(n = 10*prod(dim(t_NL)), min = -10, max = 10), ncol = ncol(t_NL))
stack_unif1010_l <- rbind(unif_noise_1010, t_NL[1:20,])

uca_stack_lr_lunif1010 <- uca(t_stack_HLR, stack_unif1010_l, nv = 5, scale = T, limit = 100)
uca_split_lr_l_unif1010 <- uca(t_stack_HLR, list(unif_noise_1010, t_NL[1:20,]), nv = 5, scale = T, limit = 100)
pos_stack_lr_lunif1010 <- pos_corr(uca_stack_lr_lunif1010$vectors, uca_split_lr_l_unif1010$vectors)
diff_stack_lr_lunif1010 <- pos_stack_lr_lunif1010 - uca_split_lr_l_unif1010$vectors

LR_unif_01_plot <- plotEigenfaces2(
rbind(
toEigenfaces(svd_t_stack_HLR$v)[, alpha := "PCA Target"],
toEigenfaces(svds(scale(stack_unif1010_l), k = 5, which ="LA" )$v)[, alpha:= "PCA Stack"],
toEigenfaces(pos_stack_lr_lunif1010)[, alpha := "Stack 0-1"],
toEigenfaces(uca_split_lr_l_unif1010$vectors)[, alpha := "Split 0-1"],
toEigenfaces(diff_stack_lr_lunif1010)[, alpha := "Diff"]), title = "Target: Happy L/R. Bg: Left with Uniform(-10,10) Noise")

ggsave("results/LR_20L_10x_unif1010.png", LR_unif_01_plot,  width = 10, height = 11, units = "in")

```

* background: various left faces

```{R}
afraid_left_files <- paste0(kdef, sapply(list.files(kdef), function(zz) paste0(zz,"/",zz,"AFHL.JPG")))
angry_left_files <- paste0(kdef, sapply(list.files(kdef), function(zz) paste0(zz,"/",zz,"ANHL.JPG")))
disgust_left_files <- paste0(kdef, sapply(list.files(kdef), function(zz) paste0(zz,"/",zz,"DIHL.JPG")))
sad_left_files <- paste0(kdef, sapply(list.files(kdef), function(zz) paste0(zz,"/",zz,"SAHL.JPG")))

afraid_left %<-% readImage(afraid_left_files, 50, 68)
angry_left %<-% readImage(angry_left_files, 50, 68)
disgust_left %<-% readImage(disgust_left_files, 50, 68)
sad_left %<-% readImage(sad_left_files, 50, 68)

t_AFL <- Rfast::transpose(afraid_left)
t_ANL <- Rfast::transpose(angry_left)
t_DIS <- Rfast::transpose(disgust_left)
t_SAD <- Rfast::transpose(sad_left)

stack_left <- rbind(t_NL, t_AFL, t_DIS, t_SAD)

svd_t_stack_HLR <- svds(scale(t_stack_HLR), k = 5, which = "LA")
pca_stack_left <- svds(scale(stack_left), k = 5, which = "LA")
uca_HLR_stack_all_left <- uca(t_stack_HLR, stack_left,nv = 5, method = "data", scale = T, limit = 100)
uca_HLR_split_all_left <- uca(t_stack_HLR, list(t_NL, t_AFL, t_DIS, t_SAD),nv = 5, method = "data", scale = T, limit = 100)
pos_HLR_stack_all_left <- pos_corr(uca_HLR_stack_all_left$vectors, uca_HLR_split_all_left$vectors)
diff_stack_split_all_left <- pos_HLR_stack_all_left - uca_HLR_split_all_left$vectors

all_left_plot_dat <- rbind(
toEigenfaces(svd_t_stack_HLR$v)[, alpha := "PCA Target"],
toEigenfaces(pca_stack_left$v)[, alpha := "PCA Bg Stack"],
toEigenfaces(pos_HLR_stack_all_left)[, alpha := "UCA Stack"],
toEigenfaces(uca_HLR_split_all_left$vectors)[, alpha := "UCA Split"],
toEigenfaces(diff_stack_split_all_left)[, alpha := "Stack - Split"])


ggsave("happy_lr_all_emotions_left.png", plotEigenfaces2(all_left_plot_dat, "Target: Happy Left/Right. Background: Split/Stack all Left other Emotions"), width = 11, height = 10, units = "in")

```

* Generate $X_1 \sim MVN(0, \Sigma_1)$
* for some $c$, generate $X_2 := MVN(0, cI - \Sigma_2) $


# experiments:

```{R, fig.height=3.4, fig.width = 12}
pca_HLR <- svds(scale(t_stack_HLR), k = 5)$v
plotEigenfaces(toEigenfaces(pca_HLR,25, 34), "", 1)
```

```{R, fig.height=3.4, fig.width = 12}
left_only <- uca(t_stack_HLR, t_NL, nv = 5, method = "data", scale = T, limit = 100)
plotEigenfaces(toEigenfaces(left_only$vectors, 25, 34), "", 1)
```

```{R, fig.height=3.4, fig.width = 12}
happy_left_only <- uca(t_stack_HLR, t_HL, nv = 5, method = "data", scale = T, limit = 100)
plotEigenfaces(toEigenfaces(-happy_left_only$vectors, 25, 34), "", 1)

```


```{R, fig.height=3.4, fig.width = 12}
dim(t_HL)
bg_HL <- t_HL + matrix(runif(prod(dim(t_HL)), -.05, .05), ncol = ncol(t_HL))
temp <- uca(t_HL, bg_HL, nv = 5, scale = T, limit = 100)

plotEigenfaces(toEigenfaces(-temp$vectors, 25, 34), "", 1)
```

```{R, fig.height=6.8, fig.width = 12}
bg_HL <- t_HL + matrix(runif(prod(dim(t_HL)), -.05, .05), ncol = ncol(t_HL))
bg_HL <- bg_HL[1:35,]
bg2 <- matrix(runif(40*nrow(t_HL)*ncol(t_HL), -1, 1), ncol = ncol(t_HL))

temp_split <- uca(t_HL, list(bg_HL, bg2), nv = 5, scale = T, limit = 60)
temp_stack <- uca(t_HL, rbind(bg_HL, bg2), nv = 5, scale = T, limit = 100)
temp_stack2 <- uca(t_HL, bg2, nv = 5, scale = T, limit = 100)

temp_stack$tau
temp_dat <- rbind(toEigenfaces(temp_split$vectors,25, 34)[, alpha := "split"],
                  toEigenfaces(temp_stack$vectors, 25,34)[, alpha:="stack"],
                  toEigenfaces(temp_stack2$vectors, 25,34)[, alpha:="bg2 only"])

plotEigenfaces2(temp_dat, title = "")
```



