# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

arma_qr <- function(X) {
    .Call(`_uca_arma_qr`, X)
}

arma_svd <- function(X) {
    .Call(`_uca_arma_svd`, X)
}

arma_score <- function(A, B) {
    .Call(`_uca_arma_score`, A, B)
}

broken_svd_cpp <- function(left, right, nv) {
    .Call(`_uca_broken_svd_cpp`, left, right, nv)
}

multiple_score_calc_cpp <- function(left, right, right_u, right_d, B, tau) {
    .Call(`_uca_multiple_score_calc_cpp`, left, right, right_u, right_d, B, tau)
}

gr_fun_cpp <- function(t_A, t_B, B, right, right_u, right_d, tau) {
    .Call(`_uca_gr_fun_cpp`, t_A, t_B, B, right, right_u, right_d, tau)
}

obj_fun_cpp <- function(t_A, t_B, B, right, right_u, right_d, tau) {
    .Call(`_uca_obj_fun_cpp`, t_A, t_B, B, right, right_u, right_d, tau)
}

